import Head from "next/head";
import Image from "next/image";
import { allURI } from "../assets/apiKeys";
import TopHeader from "../components/TopHeader";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import { Movie, MoviePropsType, ObjType, UriType } from "../utilities/types";
import Banner from "./banner";
import { useFetchMovies } from "../hooks/useFetchMovies";
import useStorage from "../hooks/useStorage";
import Movies from "./movies";

const Home = ({ netflixOriginals, movieObjects }: MoviePropsType) => {
  const { setMovieObjects } = useStorage();
  setMovieObjects(movieObjects);

  return (
    <div className="home_mainContainer" id="globalLoader">
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner netflixOriginals={netflixOriginals} />
      <Movies />
    </div>
  );
};

export default Home;

// server-side-rendering : SSR
export const getServerSideProps = async (context: any) => {
  const { req, res } = context;

  let movieObjects = {} as ObjType;

  const promiseResponse = await Promise.all(
    allURI.map(async (uri: UriType) => {
      const getMoviesData = await fetch(uri?.movieURL);
      const jsonConvertedData = await getMoviesData.json();
      movieObjects[uri?.movieType] = jsonConvertedData?.results;
    })
  );

  return {
    props: {
      netflixOriginals: movieObjects?.netflixOriginals,
      movieObjects: movieObjects,
    },
  };
};



//::: code commented for further use:::

  // res.setHeader(
  //   "Cache-Control",
  //   "public, s-maxage=10, stale-while-revalidate=59"
  // );
